In [1]:
import numpy as np 
import pandas as py 

In [2]:
from tensorflow.keras import datasets

In [3]:
(x_train,y_train),(x_test,y_test)= datasets.mnist.load_data()

In [4]:
x_train

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [5]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [6]:
x_train.shape

(60000, 28, 28)

In [7]:
x_test.shape

(10000, 28, 28)

In [8]:
width,height =28,28
input_shape =(width, height,1)

In [9]:
input_shape

(28, 28, 1)

In [10]:
x_train = x_train.reshape(x_train.shape[0],height,width,1)
x_test = x_test.reshape(x_test.shape[0],height,width,1)


In [11]:
x_train.shape

(60000, 28, 28, 1)

In [12]:
y_train.shape

(60000,)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_val,y_train,y_val =train_test_split(x_train,y_train,test_size =0.1)


In [14]:
len(x_val)

6000

In [15]:
x_train=(x_train-x_train.mean())/x_train.std()
x_val=(x_val-x_val.mean())/x_val.std()
x_test=(x_test-x_test.mean())/x_test.std()


In [16]:
from tensorflow import keras

In [17]:
num_labels =10
y_train =keras.utils.to_categorical(y_train)

In [18]:
y_train

array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [19]:
y_val =keras.utils.to_categorical(y_val)
y_test =keras.utils.to_categorical(y_test)


In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input, Conv2D, MaxPooling2D, AveragePooling2D




In [21]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5, 5), strides =(1, 1), activation= 'tanh', input_shape =(28, 28, 1)))

model.add(AveragePooling2D(pool_size =(2, 2), strides= (1, 1)))

model.add(Conv2D(16, kernel_size = (5, 5), strides= (1, 1), activation = 'tanh'))

model.add(AveragePooling2D(pool_size =(2, 2), strides= (2, 2)))

model.add(Conv2D(120, kernel_size= (5, 5), strides= (1, 1), activation ='tanh'))

model.add(Flatten())

model.add(Dense(84, activation = 'tanh'))

model.add(Dense(num_labels, activation = 'softmax'))



In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 6)         156       
                                                                 
 average_pooling2d (AverageP  (None, 23, 23, 6)        0         
 ooling2D)                                                       
                                                                 
 conv2d_1 (Conv2D)           (None, 19, 19, 16)        2416      
                                                                 
 average_pooling2d_1 (Averag  (None, 9, 9, 16)         0         
 ePooling2D)                                                     
                                                                 
 conv2d_2 (Conv2D)           (None, 5, 5, 120)         48120     
                                                                 
 flatten (Flatten)           (None, 3000)              0

In [25]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer='adam', metrics = ['accuracy'])

In [27]:
history = model.fit(x_train,y_train, batch_size = 32,epochs = 5, verbose = 1 , validation_data =(x_val, y_val))

Epoch 1/5
1688/1688 [==============================] - 48s 29ms/step - loss: 0.0502 - accuracy: 0.9839 - val_loss: 0.0653 - val_accuracy: 0.9812
Epoch 2/5
1688/1688 [==============================] - 59s 35ms/step - loss: 0.0491 - accuracy: 0.9842 - val_loss: 0.0776 - val_accuracy: 0.9788
Epoch 3/5
1688/1688 [==============================] - 49s 29ms/step - loss: 0.0484 - accuracy: 0.9848 - val_loss: 0.0693 - val_accuracy: 0.9805
Epoch 4/5
1688/1688 [==============================] - 49s 29ms/step - loss: 0.0459 - accuracy: 0.9857 - val_loss: 0.0752 - val_accuracy: 0.9780
Epoch 5/5
1688/1688 [==============================] - 50s 30ms/step - loss: 0.0474 - accuracy: 0.9854 - val_loss: 0.0713 - val_accuracy: 0.9773


In [28]:
score = model.evaluate(x_test, y_test, verbose =1)

313/313 [==============================] - 4s 14ms/step - loss: 0.0478 - accuracy: 0.9842


In [29]:
score

[0.04782944172620773, 0.9842000007629395]